name: Clear Main Branch

on:
  workflow_dispatch:  # Trigger manually from GitHub UI

jobs:
  clear:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Delete all files
        run: |
          git rm -rf .
          rm -rf * .[^.]* || true  # Remove everything including hidden files, ignore errors

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "Clear main branch"
          git push origin main
