name: Move Unzipped Folder Contents to Root

on:
  workflow_dispatch:

jobs:
  move:
    name: Move Folder Contents to Root
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Move contents to root
        run: |
          mv -n Bwm-Bwm-trekker-6f70a5dea5e66e8712f51cb4c8dbd1a4d0a76cd9/* .
          rm -rf Bwm-trekker-6f70a5dea5e66e8712f51cb4c8dbd1a4d0a76cd9
      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Move unzipped folder contents to repo root" || echo "No changes to commit"
      - name: Push to main branch
        run: |
          git push origin HEAD:main
